name: kestrl
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_fonts: ^5.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  line_icons: ^2.0.3
  path_provider: ^2.1.3
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  csv: ^6.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
